### ISSUE TITLE
dmg on Mac

### ISSUE THREAD

**Issue by andre68723** [Xiphe/budgetbudget#60]
Hi,

thanks for the nice tool
I tested the DMG, unfortunately it does not come up with (console)

`Not allowed to load local resource: file:///Applications/BudgetBudget.app/Contents/Resources/app.asar/build/index.html%23undefined
`

Version 1.0.0-beta.2

Thanks, Andre

**Comment by Xiphe** [comment]
Hey @andre68723 

Glad you like the tool. I'm just releasing a fix for this (1.0.0-beta.3).

Background: Unfortunately this issue is only in the production build that why I have not found it in local testing :( Especially funny since I just moved up from `alpha` and now the first beta release is not usable 😂

**Comment by Xiphe** [comment]
Hey @andre68723 
out of interest, how did you get the error message?
I can't open the devtools in production.

**Comment by andre68723** [comment]
attached
![budgetbudget](https://user-images.githubusercontent.com/16468234/93189925-09f2d480-f743-11ea-8295-2c035059ecfc.png)

**Comment by Xiphe** [comment]
Ah! Thats really interesting. Thanks for sharing!

So this only worked because the app did not start properly and therefore did not change the default electron menu. 
The custom BB production menu does not include the dev-tools. I should probably change that.
